### ISSUE TITLE
Batching actions in relation to effects

### ISSUE THREAD

**Issue by victornoel** [ngrx/effects#104]
This is a spin-off of ngrx/store#178 but in relation to the effects.

The problem I am encountering is the following:
 - I am using `redux-batched-actions` (i.e., an implementation of the pattern discussed in ngrx/store#178) to have batch actions applied all at once on the store.
 - since batchActions relies on the introduction of a fake (batch) action, it means the effect doesn't react to the dispatching of each of the batched actions (because the batched actions themselves are not dispatched).

It would be great if this use case could be doable with ngrx.

Either this could be solved as with the reducers via a simple library that makes the effects being triggered also for batched actions, either ngrx needs to be changed… I don't know at all enough about ngrx to answer that questions, hence the current issue :)

**Comment by karptonite** [comment]
You might be able to solve this with rxjs buffering on time or count: see for example http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-bufferCount

**Comment by victornoel** [comment]
@karptonite I'm not sure I see the link with triggering effects when batch actions are dispatched... Could you expend a bit on it for me to understand? Thanks!

**Comment by karptonite** [comment]
Well, it may be that I don't understand exactly what is going on with the batching. Say you have an action LOAD_IMAGE, that triggers an effect that loads an image, then dispatches LOAD_IMAGE_SUCCESS. Now say you want to batch your requests, so you don't load each image separately. Rather than using some sort of fake batched action, you could dispatch each LOAD_IMAGE action separately, but then group them together with bufferTime or some other buffering method--then you could do one request for a set of images, and instead call something like LOAD_IMAGES_SUCCESS.

**Comment by maxime1992** [comment]
@karptonite a good example is when you normalize data.

**For example**
- you dispatch an action `FETCH_WORKSPACE`
- catch it within an effect
- normalize the data (let say that it returns a workspace and a users list)
- return in your effect an `Action` object like that : 
```
batchActions([
    { type: 'FETCH_WORKSPACE_SUCCESS', payload: workspace },
    { type: 'FETCH_USERS_SUCCESS', payload: users }
])
```

Of course, we could wrap that into a higher action and handle that action from many reducers.
But the idea is to be more clear and have the possibility to reuse those splitted actions.

So in this case, I'm not sure it's a problem to solve by using observables but really something related to `ngrx/effects` because it cannot catch actions that we wrap into some `batchActions` function.

**Comment by karptonite** [comment]
I understand now. As you say, your best option is probably to handle that by having a higher order reducer that is handled by multiple reducers. But it does mean you could end up with a long list of actions handled by the user reducer, for example.

**Comment by karptonite** [comment]
But looking at this again, why does your patched action have to be a fake action? Could it be a real action that takes as a payload an array of actions (each with their own payload)? Then it seems to me that maybe it could be caught by effects. Now I'm really interested in this, because I'm also running into the exact issue you are describing.

**Comment by karptonite** [comment]
@victornoel @maxime1992 OK, I just implemented batching at my end. I think I now understand the problem, but I'm not certain. Correct me if I'm mistaken, but there appears to be no problem having a an Effect emit a batch of actions.

The problem comes when you want to batch actions, and then have one of those batched actions caught by an effect. I now understand the problem, but I'm having trouble thinking of a time when you might want one action from a batch to trigger another effect. The purpose of batching, I thought, was to ensure that you don't have an inconsistent state when some but not all data is processed by a reducer. When you are triggering an effect, you are almost always doing something that will take some time, and you probably aren't concerned with inconsistent state. Can you describe a case when you dispatch a batch of actions in your app, and you want one of those actions to be caught by an effect?

In case it isn't clear, I'm definitely not trying to be difficult, I'm just trying to understand the situation.

**Comment by maxime1992** [comment]
> The problem comes when you want to batch actions, and then have one of those batched actions caught by an effect

Yes !

> The purpose of batching, I thought, was to ensure that you don't have an inconsistent state when some but not all data is processed by a reducer

Totally :+1: 

> you probably aren't concerned with inconsistent state

Yes we are concerned by inconsistent store as we normalized our data and then we use selectors to generate our nested objects needed for the view.

> Can you describe a case when you dispatch a batch of actions in your app, and you want one of those actions to be caught by an effect?

I don't remember right now were we first thought of that. @victornoel do you remember exactly why we needed that ?

> In case it isn't clear, I'm definitely not trying to be difficult, I'm just trying to understand the situation.

It's nice talking with you about this problem and I understand that we weren't totally clear, no pb :)

**Comment by victornoel** [comment]
@karptonite, thank you for taking the time to understand our problem :)

Basically there was two reasons for opening this issue:
 - it seemed a good idea, for consistency, to have batched actions to trigger effects like any normal action. As you said, the batching behaviour is only making sense in the context of reducers, not effects (i.e. having all the reducers applied before anything else is triggered) but it doesn't mean there is no need for effects to be triggered in order to have a homogeneous behaviour. And it seemed to us that we couldn't achieve that without entering into the depths of ngrx, and maybe even without modifying it, hence the present issue.
 - Our particular use case is simply that we have some actions that need to be dispatched together to keep the store consistent and it happens that other actions have to be dispatched at the same time.
   - the easy solution is to have a dispatch for the batched actions and one for the effect triggering actions
   - but for correctness and maintainability reasons, it is difficult to verify each and everytime we modify the dispatches that we are doing things correctly.
   - note that we haven't yet found ourselves in the situation where an actions that was updating the store (and that should be dispatched atomically with some others) was at the same time triggering an effect, so the current situation is not blocking, but I don't think why it wouldn't happen (i.e., we are back to my first point about consistency of ngrx behaviours :).

For the record, I personally think that batch actions should be implemented as part of ngrx and not just a library like it is currently the case. Mainly because of my first point and to ensure the actual behaviour of these things is the expect behaviour.

**Comment by karptonite** [comment]
I understand the issue. FYI, I'm just a user of this library, and not an extremely knowledgable one, but it is an interesting problem.

I wonder if in part this is maybe a semantic issue. When you have a batch of actions, we think of it as an action that dispatches two other action in such a way that they are handled together. But is that really what it is? Perhaps it is more instructive to think of a batched action as creating a new single action with a new type and payload that replaces the "batched" actions entirely. That means that the reason the Effects module does not catch the batched actions is that there is no such action dispatched. 

In that case, the solution might be to add a method to your effects to split batched actions.
```typescript
@Effect()
load$: Observable<Action> = this.actions$
   .splitBatchedActions()
   .ofType( users.LOAD )
```
where `splitBatchedActions()` takes the stream of actions, and looks for batched actions and splits them into multiple events, otherwise just passing the actions through.

This might not be as good as having batching baked into effects and store, but it should do the trick. I'm not sure that batching is something that the library should encourage--you could argue that it is a bit of an anti-pattern, and that the better solution would be a more comprehensive action that is handled by multiple reducers.

**Comment by victornoel** [comment]
@karptonite I don't really agree with this semantic interpretation.
The semantic of batched actions is VERY clear, since there is an implementation for it :)

The important point to me is that using batched actions has no impact at all on the definition of reducers: they are simply used as-is but in an atomic way. And this is possible because ngrx/store provides the abstractions to do that.

What I would like is that ngrx/effects provide me the same abstractions to do the same with effects, without the need to change how my effects are defined.

**Comment by victornoel** [comment]
@MikeRyan52 any comment about this? Thanks :)

**Comment by victornoel** [comment]
In the end, this is how I handled this situation

1. I defined an alternative of `Actions` (the one provided by `ngrx/effects`, I omitted `lift` because I didn't have any use for it):
```ts
@Injectable()
export class ActionsWithBatched extends Observable<Action> {
  constructor(@Inject(Dispatcher) actionsSubject: Observable<Action>) {
    super();
    this.source = actionsSubject;
  }

  ofType(...keys: string[]): ActionsWithBatched {
    return mergeMap.call(this, (action: Action) => {
        // we keep it if it is one type of one of they keys
      if (keys.includes(action.type)) {
        return Observable.of(action);
      }

      // or if it's a batch action, we keep the actions that match the keys
      if (action.type === BATCH) {
        const ac = (action.payload as Action[]).filter(a => keys.includes(a.type));
        return ac ? Observable.from(ac) : Observable.empty();
      }

      // else we skip it
      return Observable.empty();
    });
  }
}
```
2. I specified it as a provider in my main module so that it can be injected.
3. I injected it instead of `Actions` in my effects classes and used it exactly in the same way as before.

Any ways to make this simpler @MikeRyan52?

I will maybe create a clean package for batched actions and ngrx, and deploy it on npmjs.

**Comment by victornoel** [comment]
Or @brandonroberts, if you have an idea to make this simpler or more elegant, and the best would be to avoid redefining `Actions` if possible :)

**Comment by victornoel** [comment]
Something a bit more elegant I think:
```ts
@Injectable()
export class ActionsWithBatched extends Actions {
  constructor(@Inject(Dispatcher) actionsSubject: Observable<Action>) {
    super(actionsSubject);
    this.operator = new MergeMapOperator((action: Action) => {
      if (action.type === BATCH) {
        return Observable.from(action.payload as Action[]);
      } else {
        return Observable.of(action);
      }
    });
  }
}
```

But the best would be to not even have to define this… maybe exploiting `Actions.lift` to replace the `Actions` already provided by `EffectModule`…

**Comment by TheophileSketo** [comment]
I think we had a similar use case. What we ended up using is something like this. The drawback is the actions inside forkJoin are not actually dispatched.

```ts
  @Effect() initView = this.actions.ofType('INIT_VIEW_START')
    .mergeMap(action =>
      Observable.forkJoin(
        this.getData.startWith({ type: 'GET_DATA_START' }),
        this.getMoreData.startWith({ type: 'GET_MORE_DATA_START' })
      ).mergeMap(([getData, getMoreData]) => {
        if (checkSuccess(getData, getMoreData)) {
          return Observable.from([getData, getMoreData, { type: 'INIT_VIEW_SUCCESS' }]);
        } else {
          return Observable.from([...[getData, getMoreData].filter(onlyFailed), { type: 'INIT_VIEW_FAILED' }]);
        }
      })
    );

  @Effect() getData = this.actions.ofType('GET_DATA_START')
    .switchMap(action =>
      this.http.get('data')
        .map(data => ({ type: 'GET_DATA_SUCCESS' }))
        .catch(err => Observable.of({ type: 'GET_DATA_FAILED' }))
    );

  @Effect() getMoreData = this.actions.ofType('GET_MORE_DATA_START')
    .switchMap(action =>
      this.http.get('moreData')
        .map(data => ({ type: 'GET_MORE_DATA_SUCCESS' }))
        .catch(err => Observable.of({ type: 'GET_MORE_DATA_FAILED' }))
    );
)
```

**Comment by robwormald** [comment]
Please check this against NgRx v4, and if it’s still an issue, please reopen on https://github.com/ngrx/platform. Thanks! (this is worth discussing)

**Comment by rostag** [comment]
If anyone is still struggling with this issue, here's the quick and elegant solution:
https://github.com/ngrx/effects/issues/134#issuecomment-316541034

**Comment by victornoel** [comment]
@rostag yep, that's the same a what I said in https://github.com/ngrx/effects/issues/104#issuecomment-287045069 where I use the `mergeMap` operator except it is used directly inside ngrx and not as a user-declared effect.

**Comment by victornoel** [comment]
I have a complete implementation here: https://gitlab.com/linagora/petals-cockpit/blob/master/frontend/src/app/shared/helpers/batch-actions.helper.ts

I wanted to publish it as a library, but I struggled so hard to create a self-contained lib that I abandoned the idea :) the state of build tools for js/ts/ng stuffs is really horrible :/
