### ISSUE TITLE
Getting rid of {dispatch: true | false}

### ISSUE THREAD

**Issue by robertohuertasm** [ngrx/effects#124]
@MikeRyan52, I've been looking into the code and I'm wondering why we're not leveraging [this subscription](https://github.com/ngrx/effects/blob/master/src/effects-subscription.ts#L33) in order to check if we're receiving and action or not.

Something similar to this:
```ts
addEffects(effectInstances: any[]) {
    const sources = effectInstances.map(mergeEffects);
    const merged = merge(...sources);
    this.add(merged.filter(x => x).subscribe(this.store));
  }
```

The thing is that `ngrx/store` doesn't seem to control errors happening in its main subscription (it swallows them and closes the stream because of the error without you getting notified) and by using `effects` it's fairly easy that someone forgets returning an action because she's facing an issue like #101, hence causing a fatal error that will go silent.

Is there any reason by which it is more desirable to rely on `dispatch` attribute than controlling the value of the observable's return?

Thanks in advance. 

PS: If needed I'll be willing to submit a PR and update the docs while keeping backwards compatibility.

**Comment by bertofer** [comment]
The only problem I see with this is that you may not want to dispatch, even if your observable returns an action. Imagine the following scenario, where you do something with the current action:
```
@Effect()
doSomething$ = this.actions$
  .ofType(action)
  .do(whatever)
```

This observable does return an action, because the action that triggered it gets propagated through the `do` operator, but then causes an infinite loop to happen. The only way to solve that, is by specifying `{ dispatch: false }`.

I agree with your solution of `merged.filter(x => x)`, this could avoid passing errors to the store and breaking it. But in my use cases, `dispatch: false` is more to avoid infinite loops of the same action being triggered, than to avoid dispatching `undefined`

**Comment by robertohuertasm** [comment]
@bertofer, I guess you shouldn't use the `do` operator but maybe the `map` operator.

**Comment by bertofer** [comment]
Imagine I don't want to dispatch another action, I just want to navigate to a different route, by calling this.router.navigate(), which returns a boolean. The boolean will get dispatched to the store because it's not undefined, but I don't want it to.

**Comment by robertohuertasm** [comment]
In my [PR#129](https://github.com/ngrx/effects/pull/129/files#diff-64240219191914337144a75fc12e4ceeR32) you will see that the filter has been extended to only allow objects with the `type` property, so your case will never be an issue. I do duck typing although maybe we could be using type checking but I didn't want to force people to be using @ngrx/store actions, just any implementation of it will suffice.

**Comment by bertofer** [comment]
Ok @robertohuertasm that makes sense for me, to only dispatch things that come with a type property. 

I am still a bit concerned about the infinite loop if you dispatch the same action (for instance, using `do`, like in the debug example).

IMHO, I would add the filter of the actions, for "weird" things not getting dispatched to the store, but I would keep the `{ dispatch: false }` to explicitly say that, even if I return an action, I don't want it dispatched (case where you return the same action because you don't change the observable).

**Comment by karptonite** [comment]
@robertohuertasm Interesting. The issue I see is that this will create an infinite loop if someone DOES call `do`, and return the original action. 

Also, I think duck typing is the best you can do on this--if I'm not mistaken, I think that the type information is removed when the typescript is compiled.

**Comment by robertohuertasm** [comment]
@karptonite you're right. I forgot that the @nrgx/store action was just an interface.

Regarding the initial @bertofer's concern about the infinite loop, this would also happen if someone forgets about the `dispatch: false` in the decorator. So the thing is that the user has to be aware of this issue no matter if the `dispatch` flag exists or not. My point is that you have many other ways of doing what you're doing right now with the `do` operator. 

Let's say someone faces this scenario and don't know about how the library works in deep (which is normally the case). They decide to use the `do` operator and they hit the infinite loop. The fact that the `dispatch` flag exists is not preventing them from hitting the infinite loop. It's just a solution preventing them from properly use RxJs. You have other operators to avoid propagating the action.

**Comment by bertofer** [comment]
>  It's just a solution preventing them from properly use RxJs

Can you explain more why using `do` is not a proper way of using RxJs? What would be the proper way in this case?

**Comment by robertohuertasm** [comment]
@bertofer I didn't want to imply that `do` is not an operator you shouldn't use but you should know how it works. And by that I mean that whenever you're using it you'll be returning the original action (in this case). If that's not your intention then it's clearly a bad use of the operator. Your code should speak for itself. If you don't want to dispatch an action you can use the `map` operator instead. It will let you control what your finally returning.

**Comment by bertofer** [comment]
I don't see why returning the same action can be the wrong use of the operator. I just want to do something with the event, not worrying about the observable at all, so I think it's the proper use of `do`. I think you are assuming all side effects have to return an action, I disagree with that.

The doc of `do`:

> Perform a side effect for every emission on the source Observable, but return an Observable that is identical to the source.

A side effect is exactly what we are doing here.

After a `do` that just logs the current action, I don't want to dispatch the same action that came, and that's why `dispatch: false` exists, and I think it's a completely fine solution to explicitly say you don't want to dispatch.

My solution if there is no dispatch at all, would be to `mapTo(undefined)` after the do, relying on the source code of effects not dispatching it (something that is even more hidden than the `dispatch` property). 

Changing the operator to not return an action I think it's confusing, because you don't care at all about whatever the observable returns in this case, so why caring about returning something specifically different than an action?

I just think the current `dispatch` option is completely fine, and clearly represent your intentions (don't dispatch whatever comes from here). I don't think it's something just for someone who knows deeply about the library, but instead a fundamental option.

I think the real rxjs proper solution would be to just subscribe to the actions$ observable, and then do whatever I was doing inside `do` in the subscription directly, without decorating it with `@Effect`, but then you loose a lot of the benefits of having the subscriptions handled for you.

**Comment by robertohuertasm** [comment]
>  I think you are assuming all side effects have to return an action, I disagree with that.

Not at all. I'm assuming that if you return an action is because you want it to be dispatched. Hence, if you want to do some side effect without returning the action you can use `map` without `do`. The library will only dispatch if you return an action so any other case will be omitted. 

> My solution if there is no dispatch at all, would be to mapTo(undefined) after the do, relying on the source code of effects not dispatching it (something that is even more hidden than the dispatch property).

> Changing the operator to not return an action I think it's confusing, because you don't care at all about whatever the observable returns in this case, so why caring about returning something specifically different than an action?

We have to consider the context in which we're using the observable. You **know** that `effects` will dispatch any action that is returned as a result of the subscription so you have to be concerned about what you're returning.

In general terms, what I'm saying is that the `dispatch` flag is not needed at all. It wouldn't give you anything that you couldn't accomplish with the use of Rxjs. From my point of view this is just a cognitive burden.

**Comment by robertohuertasm** [comment]
@bertofer, just to be clear. My main intention with #129 is to offer a way to accomplish clean dynamic dispatching like in #101.

Getting rid of the `dispatch` flag is something I advocate for, as for me it's completely useless and redundant if #129.

**Comment by bertofer** [comment]
Yes, I understand, and completely agree that #129 is fine as a way to not propagate incorrect things to the store.

I just disagree with removing the dispatch flag ;) (Aside from the arguments above, it'd cause breaking changes). I agree it's not technologically needed, but I think it describes better your intentions than changing the operator to return something different.

**Comment by OClement** [comment]
I'm a bit late to the party, but I think this here might be the proper way to ask a question I'm seeking an answer to all the while commenting this discussion;

I, too, want to call a bit of code when certain action(s) is dispatched, without the need to dispatch a new action afterward. 

Naturally, I thought "Effect ought to do it", and found about the `{ dispatch: false }` flag. 
So, yeah I could indeed use that and have my code in a `do` operator, but then that would smell a bit; I'm not sure I would advocate the use of the `do` operator for any piece of logic more complex than a `console.log` personally, but that's me.

A note on using `map` for this; I personally think this would be wrong, as it wouldn't describe your intention; `map` is self-describing in the sense that you're transforming data, which wouldn't be the case here. Also, `map` needs you to return a value, so having to return `undefined | true | false | {} | ...`  and not doing anything with this value seems silly at best. So in that respect, `do` seems more appropriate, but again I'm not a fan of this (I'd be happy to be convinced otherwise though!)

Then there's the question of "okay fine, but then what's the advantage of having to use the `@Effect` decorator at all?". I could simply subscribe to the `Action` observable and be done with it (considering I probably won't need to ever unsubscribe from it for the app instance's lifetime)

My only concern around all this is really about best practices and the risk of creating dangerous precedent; Considering I could subscribe directly to `Actions`, not even in a class "meant to be used for/as Effects", it mean I could inject it pretty much anywhere, and I'd fear other Devs would feel it's right to jump the gun and skip some layers of the app (thus creating different code-styles/standards accross the app, as opposed to having a well structured architecture.

Thoughts?

**Comment by OClement** [comment]
@robertohuertasm 
Do we know what's happening with this?

I'm in the process of refactoring our app (and updating to Ngrx 4) and would like to know if this likely to happen or not, since it'd influence some decisions down the road;

Thanks

**Comment by robertohuertasm** [comment]
This was discarded. I don't think it's going to happen.

**Comment by OClement** [comment]
Thanks for the update
