### ISSUE TITLE
Property 'run' does not exist on type 'typeof EffectsModule'.

### ISSUE THREAD

**Issue by petersgiles** [ngrx/effects#173]
I'm getting this error when using the latest version of @ngrx/effects. 
Has 'run' been deprecated? If so is there up to data documentation?

```
Typescript Error
Property 'run' does not exist on type 'typeof EffectsModule'.
```

package.json

``` json
"@ngrx/core": "^1.2.0",
"@ngrx/effects": "^4.0.2",
"@ngrx/store": "^4.0.2",
"@ngrx/store-devtools": "^4.0.0",
```

in my reducer.ts file

``` Typescript
import { EffectsModule } from '@ngrx/effects'

import { IGlobalState, globalReducer, GlobalActions, GlobalEffects } from './global';
import { IContentState, contentReducer, ContentActions, ContentEffects } from './content';

\\ ... CODE SKIPPED

export let ApplicationRootEffects = [
  EffectsModule.run(GlobalEffects),
  EffectsModule.run(ContentEffects)
];
```

**Comment by brandonroberts** [comment]
Reigstering effects has changed in V4. See https://github.com/ngrx/platform/blob/master/MIGRATION.md

**Comment by brandonroberts** [comment]
It is reflected in the documentation for V4: https://github.com/ngrx/platform/blob/master/MIGRATION.md#ngrxeffects

**Comment by select** [comment]
You are absolutely right I skipped over the README header and went right to 
https://github.com/ngrx/effects/blob/master/docs/intro.md 
where there is no more warning. I found the the right documentation. Thanks 

But I must unfortunately say that discoverablity of  the right documentation version for rxjs and now the ngrx version too is very confusing. There are two URLs that you can find a google search and you need to be constantly aware of which link you click since it looks like you are in the right place even though there was an API change that moved the docu to new domain.

**Comment by brandonroberts** [comment]
Good point. We'll have to add the banner to the other documentation pages to point to the latest release.
