### ISSUE TITLE
Remove Angular 2 dependency

### ISSUE THREAD

**Issue by JamesHenry** [ngrx/effects#19]
Now that neither ngrx/core nor ngrx/store depend on Angular 2, it would be great if that were true for effects as well.

I am successfully using ngrx/store in my Angular 1.x app right now, and would love to introduce ngrx/effects.

It seems like the task is mostly straightforward (change OpaqueToken to String, change use of Provider constructor to object literal syntax), however the only thing I am not sure about is the use of APP_INITIALIZER here https://github.com/ngrx/effects/blob/master/lib/effects.ts#L27

Let me know your thoughts on that and I will happily submit a PR with the changes.

I have done the same for the ngrx-store-logger: https://github.com/btroncone/ngrx-store-logger/pull/9, although that didn't require any code changes.

**Comment by kylecordes** [comment]
I am thrilled by the past work mentioned here and by the possibility raised in this item. I hope this becomes a dominant name in Angular 2 related library development: only actually depend on Angular 2 if truly necessary, don't just take the dependency by default everywhere.

**Comment by MikeRyan52** [comment]
Yes, I want this as well. That's why I've been working recently to remove the Angular 2 dependency from store and core. HOWEVER, there are two issues with removing Angular 2 from ngrx/effects (one you've already pointed out):

- There is no `APP_INITIALIZER` token or equivalent feature in Angular 1 (though starting them in a `run()` function would probably suffice)
- There is no concept of multi-providers, meaning you would probably have to wire up the effects manually

Because ngrx/effects is more of a pattern than a formal library, I think in this specific instance it might be best just to create an Angular 1 version separately.

**Comment by JamesHenry** [comment]
(Disclaimer: My intended use case of Angular 1 actually involves the awesome [ng-metadata](https://github.com/ngParty/ng-metadata) library as well cc: @Hotell)

Thanks, @MikeRyan52. So yeah it seems `APP_INITIALIZER` is the real hurdle.

Regarding your second point, as you of course know ngrx/store exposes multiple providers in much the same way via its `ng2.ts` file, which does not actually depend on ng2.

Because of how awesome ng-metadata 2.0 is, we can use the multi-providers in Angular 1 today, as long as we have some kind of file which decorates them first.

Here is how I wired up ngrx/store with ng-metadata/Angular 1:

https://gist.github.com/JamesHenry/15170e718ae0608c40d5c63c12110990

As long as ngrx/effects also provided an Angular 2 DI compatible interface (without Angular 2), I could see this working in much the same way.

I don't know Angular 2 well enough to know exactly how the `APP_INITIALIZER ` could be refactored to make that possible in an Angular 2 world, but without needing Angular 2. (As you say, for Angular 1 I could imagine us adding something to ng-metadata to translate that into a run block.)

The only thing which occurs to me right now (which I am sure would not be the most popular suggestion) is that the app developer becomes responsible for implementing that part themselves...

**Comment by christophercr** [comment]
Hi, I've just seen that v1.1.1 has been released. In such version the state-updates.ts there is now an @injectable which in fact introduces again the issue that was supposed to be solved by the PR mentioned in this issue (all the ng2 specifics should be in the ng2.ts).

Is it be possible to extract that @injectable to the ng2.ts?

**Comment by MikeRyan52** [comment]
Yes, unfortunately it caused an unexpected breaking change for developers who were simply importing `StateUpdates` and providing it:

```ts
import { StateUpdates } from '@ngrx/effects';

@Component({
  providers: [ StateUpdates ]
})
export class MyComponent { }
```

I plan on re-removing the `@Injectable()` decorator in v2.0 which will land with Angular 2 RC 5. This will also be the release that removes the dependency on `APP_INITIALIZER`

**Comment by kylecordes** [comment]
It's unfortunate when a previously removed dependency sneaks back in. On large projects it is very helpful to set up automatic dependency guards, for example ways to make a build fail if a previously banned dependency has been accidentally re-added. This is a pretty small code base though, with only a handful of people reviewing code, so that complexity is almost certainly not warranted here.

**Comment by JamesHenry** [comment]
Thanks for trying, @MikeRyan52!

Of course, ironically, Angular 2 RC 5 ended up bringing in more things to make removing Angular 2 impractical. Rob adding back Angular 2 as a dependency of the main ngrx project so I am going to close this and make my peace with it 😄
