### ISSUE TITLE
Actions in Wrong Order

### ISSUE THREAD

**Issue by kurigohan** [ngrx/effects#58]
I just update to ngrx/effects 2.0 and I'm encountering a strange issue. It seems like actions that are dispatched by an effect are being executed before the listened action.

For example, I have an effect that listens to FORM_SUBMIT and then dispatches FORM_SUBMIT_SUCCESS after doing some stuff. However, the FORM_SUBMIT_SUCCESS action ends up occurring before FORM_SUBMIT. It seems like the effect is being run before the listened action passes through the reducers.

**Comment by jogboms** [comment]
Same issue I am having. I actually thought I was doing something wrong with
mine days back when I tried it out. Haven't given it a go again.

**Comment by awerlang** [comment]
How are you verifying FORM_SUBMIT_SUCCESS occurs before FORM_SUBMIT? Paste here the effect and other parts you deem as important, it might help.

**Comment by jogboms** [comment]
In my case, I noticed it only occurred in effects without any asynchronous
calls. Just spitting out a modified payload immediately as it runs.

**Comment by kurigohan** [comment]
So my effects are non-async at the moment so the issue might be for these cases only, like jogboms mentioned.

```javascript
function createForm(state = initialState, action: Action) {
    switch (action.type) {
    case SUBMIT_FORM: 
      console.log('submit form');
      return state;

    case SUBMIT_FORM_SUCCESS:
      console.log('submit form success');
      return action.payload;

    default: 
      return state;
  }
}
```
```javascript
@Effect() createSomething$ = this.actions$
    .ofType(SUBMIT_FORM)
    .map(action => {
      return submitCreateFormSuccess(this.somethingService.create(action.payload));
    });
```

**Comment by stephenlautier** [comment]
Similarly we are having the same issue which enters first within the effect then within the reducer.
The weird thing is that the same piece of code runs on 2 different projects, on one it works fine (reducer > effect) and within the other the other way round (effect > reducer).

Should it be guaranteed that the reducer is first triggered and not the effect, or not?

**Comment by akomm** [comment]
I confirm this. Confirmed it using the ngrx log monitor AND logging via meta reducer around my root reducer. Those who do not encounter this issue should test if that is due to async delays.

**Comment by MikeRyan52** [comment]
This is a confirmed bug, thanks for the reports everyone!

Unfortunately this probably isn't going to be fixed _soon_. Dispatching an action is synchronous both for effects and your state. Once multiple actions start being dispatched synchronously there simply is not a performant way to guarantee that all subscribers will be notified in a consistent order. Once the rxjs marble testing tools are easier to integrate into projects I will add a failing test case for this bug so that it can be tracked.

In the mean time, I want to leave everyone with a few tips about effects and redux data flow in general:

A major underlying pattern of Redux is event sourcing. All changes in state should be captured in an event. If you have found that you need to dispatch multiple actions simultaneously you would be better served by creating a new action type. Actions can have a many-to-many relationship with both reducers and effects.

If many actions cause the same state change in a reducer you can stack cases:
```ts
switch (action.type) {
  case LOGIN_SUCCESS:
  case AUTH_TOKEN_VERIFIED:
     return newState;
}
```

If many actions trigger the same effect, `ofType` can accept multiple types:
```ts
actions$.ofType(LOGIN_SUCCESS, AUTH_TOKEN_VERIFIED)
```

New action types are cheap to create. Describe all events using actions. Don't be afraid to reduce the same action in multiple reducers or to have many actions trigger effects. That's what makes @ngrx/store and @ngrx/effects so powerful in large applications.

Lastly, if you are absolutely sure you cannot merge multiple actions into a new action and you _must_ dispatch multiple actions at the same time and they _must_ be in the same order then you can alter the behavior of your effect stream to occur on an async schedule:

```ts
import 'rxjs/add/operator/observeOn';
import { async } from 'rxjs/scheduler/async';

myEffectStream$.observeOn(async);
```

**Comment by peterbakonyi05** [comment]
I bumped into the same issue last week, even created another [issue](https://github.com/ngrx/store/issues/279) on the ngrx/store library because I couldn't find this one.

I reported another issue that seems to be the root cause of the problem: https://github.com/ReactiveX/rxjs/issues/2155

Maybe you can follow that one to understand better why we have issues like that. :)

**Comment by MikeRyanDev** [comment]
Fixing this in @ngrx/effects v4

**Comment by timblakely** [comment]
Just curious: will the fix in v4 apply to @ngrx/store as well? Though I'm not using @ngrx/effects, I am seeing this behavior just like ngrx/store#279

**Comment by robwormald** [comment]
Please check this against NgRx v4, and if it’s still an issue, please reopen on https://github.com/ngrx/platform. Thanks!

(pretty sure it's fixed)
