### ISSUE TITLE
startWith operator not passing action to reducer

### ISSUE THREAD

**Issue by RyanMcDonald** [ngrx/effects#65]
I'm trying to run an effect on startup that sets the loading status of my 'scene' objects to true, and then when it's finished loading, sets the loading status to false. For some reason, when I use `startWith`, that action is not making it to the reducer, so `loading: true` is never executed. I took some of this code from the example-app.

Action:
```javascript
export class LoadAllScenesAction implements Action {
  type = ActionTypes.LOAD_ALL_SCENES;

  constructor() { }
}
```

Reducer:
```javascript
export function reducer(state: ScenesState = initialState, action: sceneActions.Actions): ScenesState {
    // LOAD_ALL_SCENES never makes it here
    console.log('SCENE ACTION IN REDUCER', action.type);
    ...
    case sceneActions.ActionTypes.LOAD_ALL_SCENES:
          return Object.assign({}, state, {
            loading: true
          });
    ...
}
```

Effect:
```javascript
@Effect() loadAllScenes$: Observable<Action> = this.actions$
    .ofType(sceneActions.ActionTypes.LOAD_ALL_SCENES)
    .startWith(new sceneActions.LoadAllScenesAction())
    .mergeMap(action => {
      return this.hueService.loadAllScenesWithLightStates()
        .map((scenes: Scene[]) => new sceneActions.LoadScenesSuccessAction(scenes))
        .catch(error => {
          this.errorHelper.handleError({ error, action });
          return Observable.of(new sceneActions.LoadAllScenesFailAction());
        });
    });
```

What am I missing?

**Comment by wizardnet972** [comment]
Hi @RyanMcDonald ,

'startWith' operator make a effect to trigger immediately on startup.

In the app example, this LOAD action is used for two scenarios:

**On startup**
App don't need to indicate that  it's load the collection because **the app is in loading state anyway**.

** When retrieve a book **
When you retrieve a book this LOAD is coming to action, because here you need to indicate that you in loading status. [see here](https://github.com/ngrx/example-app/blob/f15733dd3f3f0346405fdfbd214ea73c6fef00dc/src/app/guards/book-exists.ts#L59)

**Anyway,**
if you still want to indicate loading, you should add 'do' to your effect like this:

```
@Effect() 
loadAllScenes$: Observable<Action> = this.actions$
    .ofType(sceneActions.ActionTypes.LOAD_ALL_SCENES)
    .startWith(new sceneActions.LoadAllScenesAction())
    .do(() => this.store.dispatch(new sceneActions.LoadAllScenesAction()))
    .mergeMap(action => {
      return this.hueService.loadAllScenesWithLightStates()
        .map((scenes: Scene[]) => new sceneActions.LoadScenesSuccessAction(scenes))
        .catch(error => {
          this.errorHelper.handleError({ error, action });
          return Observable.of(new sceneActions.LoadAllScenesFailAction());
        });
    });
```

**Comment by MikeRyan52** [comment]
@wizardnet972 is correct :)
