### ISSUE TITLE
Effects and ActivatedRoute

### ISSUE THREAD

**Issue by baio** [ngrx/effects#78]
Angular 2.1.2
Angular-router 3.1.2
    "@ngrx/core": "1.2.0",
    "@ngrx/effects": "2.0.0",
    "@ngrx/store": "2.2.1",

Hi Im not sure is it ngrx/effects issues or angular router but when I do this

```
  constructor(
    private actions$: Actions,
    private router: Router,
    private activatedRoute: ActivatedRoute,
  ) {

....
  @Effect()
  someEffect$ = this.actions$.ofType(...).map(_ =>
        //want to navigate relatively
       this.router.navigate(["items"], { relativeTo: this.activatedRoute });
);

}
```
`this.activatedRoute` always points out to root ie AppComponent routing. 
I really don't know how effectively make relative navigation inside effect methods, so please any suggestions.

**Comment by DzmitryShylovich** [comment]
> this.activatedRoute always points out to root ie AppComponent routing.

it's by design

**Comment by brandonroberts** [comment]
If you want to navigate relatively and your dispatching an action from a Component, you need to provide the `ActivatedRoute` from that component in your payload and use it in your effect.

**Comment by dfreier** [comment]
If you want to change the route relative from whats displayed at the moment then this works with Angular 4:
```
import { Injectable } from '@angular/core';
import { Actions, Effect } from '@ngrx/effects';
import { Store, Action } from '@ngrx/store';
import { Router } from '@angular/router';
import { go } from '@ngrx/router-store';

@Injectable()
export class SomethingEffects {

  @Effect() saveSomething$ = this.actions$
    .ofType('SAVE_SOMETHING')
    .withLatestFrom(this.store.select(state => state.currentSomething))
    .switchMap(([action, currentSomething]) => this.myApi.putSomething(currentSomething)
      .concatMap(savedSomething => [success(savedSomething), go('../', {}, {relativeTo: this.deepestActivatedRoute})])
      .catch(err => error(err))
    );

  constructor(
    private myApi: MyApi,
    private store: Store<AppState>,
    private actions$: Actions,
    private router: Router
  ) { }

  private get deepestActivatedRoute() {
    let route = this.router.routerState.root.firstChild;
    
    while (route.firstChild) {
      route = route.firstChild;
    }

    return route;
  }
}
```

@brandonroberts: I think putting the activated route object into action payload must be a very explicit decision. In general actions should be serializable, otherwise one could lose some of the greatest benefits of Redux. It is okay to put non-serializable payload into actions if the effect is the only receiver. But as soon as the action makes its way up to a reducer things get awkward. 

It would be nice to have a native angular API to extract the truly activated route from everywhere...
