### ISSUE TITLE
Simpler example of using the @Effect() decorator?

### ISSUE THREAD

**Issue by cquillen2003** [ngrx/effects#83]
Can someone please provide a simpler example of using the @Effect() decorator.  I simply want to make a single http call after "hearing" a specific action dispatched and handle that http requests' response right here in the effect.

The current example somehow makes an http call and dispatches an action in a big mess of rxjs operators.  I have a pretty good understanding of observables after watching a couple of Jafar Husain's talks on the subject.  IMHO, this library needs to provide examples that are much simpler and readable.

**Comment by fxck** [comment]
What exactly is a big mess of rxjs operators? There's a comment above each, explaining why it is there. It is almost as simple as it gets. You could remove couple of things:

```typescript
  @Effect() login$ = this.actions$
      .ofType('LOGIN')
      .switchMap(payload => this.http
        .post('/auth', payload)
        .map(res => ({ 
          type: 'LOGIN_SUCCESS', 
          payload: res.json() 
        }))
      );
```

But you'd be shooting yourself in the foot, as you'd need to catch errors in proper app anyway.

**Comment by cquillen2003** [comment]
Two maps and a switchMap for a simple http call is unnecessary.

Using array/observable operators in this way is going against their purpose.  Observables are for push collections of MULTIPLE values.  A login event does not produce multiple values, so an observable is overkill here.

Treating everything as a stream is forcing a square peg into a round hole IMHO.  It's important to use observables, promises, functions, and iterators appropriate to the use case: single value vs. multiple values and push vs. pull.  The RxJs docs themselves point out where observables fit in:

http://reactivex.io/rxjs/manual/overview.html

Jafar Husain's latest talk describes the use case for observables really well too.  He also explains how promises will soon be cancellable.

https://www.youtube.com/watch?v=3pKNRgResq0

**Comment by fxck** [comment]
https://github.com/angular/angular/issues/5876 good luck and have fun

**Comment by fxck** [comment]
Also if you have problem with everything being an observable, which is the whole point of this whole library and ecosystem around it, you might want to look into https://github.com/angular-redux/ng2-redux and fetch. Me, having used ngrx extensively since the very beginning, I have never ever felt like forcing square peg into a round hole.

**Comment by jogboms** [comment]
Saying square peg in a round hole here is just off point. Understand why we
have @Effects in the first place. We utilize the redux pattern, if you've
done that extensively you would see how important it is to deal with side
effects. The whole purpose of Observables here is to handle data
composition more efficiently and in a more readable way.

So no, when you feel the need to do things the more imperative way, then
fine, use the fetch api and handle the promise.

I've been using ngrx packages from when I realized everything is a stream
and began to see most things as is and there are points where it isn't
really needed too and there is also a talk by @blesh at ng-europe (I think)
that throws more light on this but when you have to compose multiple logic
gates using the redux pattern, you should see the importance of Observables
here.

IMHO.

**Comment by jogboms** [comment]
Why the way, when you said a login event does not produce any multiple
values, it's all about the effects that single event can cause to your
entire app. I can think of a dozen already for a fairly-sized app (which
should be a factor for even choosing to use the Redux pattern in the first
place). Instead of handling all these effects of carrying out a login event
in a gigantic callback, instead see the effects that should take place
afterwards as a stream of composed actions that can call on order actions
that in turn gets passed to multiple reducers charged with making changes
to the state of your store.

**Comment by cquillen2003** [comment]
A stream of states and a stream of actions makes a lot of sense to me, so don't get me wrong.  I'm a big fan of Ngrx.  And with observables being on the standards track, I'd rather stick with Ngrx over Redux.

I got off track with my comments above.  Can someone show how to make an http call using the fetch spec as an @Effect?

**Comment by MikeRyan52** [comment]
@cquillen2003 All observable operators that accept an observable will typically accept a promise as well. Here is the basic example adapted to use `fetch` instead of the Http service:

```ts
  @Effect() login$ = this.actions$
    .ofType('LOGIN')
    .mergeMap(payload => 
      fetch('/auth', {
        method: 'POST',
        body: JSON.stringify(payload)
      })
      .then(res => res.json())
      .then(res => ({ 
        type: 'LOGIN_SUCCESS', 
        payload: res
      }))
      .catch(res => ({
        type: 'LOGIN_FAILURE'
      }))
    );
```

With ngrx/effects you aren't describing just one Http request; instead you are describing all of the times your application will make the same request over the lifetime of an application's instance. A stream of Http requests if you will.

**Comment by fxck** [comment]
..and you'll end up with the same amount of code, except you had to bring in another third party library, while losing all the advantages Http/observables bring by default.

I think the real problem here is not the length of the code or mess of operators, but understanding or both observables and redux patterns.

**Comment by cquillen2003** [comment]
@MikeRyan52 Thank you for the example.

@fxck I agree.  It's the advanced operators on observables that I don't yet understand.  I understand map, filter, concatAll, mergeAll, and switchLatest from Jafar's talks, but I don't understand switchMap and mergeMap.

Can either of you help me understand what switchMap and mergeMap are doing in these examples?  Lastly, how are you able to trigger a new action with only ({ type: 'LOGIN_FAILURE' }) as the callback function?

**Comment by fxck** [comment]
mergeMap is one of the most common and easiest operators, it's async version of map... basically instead of map x to you, it's mergeMap x to the result of y(where you is either observable or promise)

**Comment by fxck** [comment]
https://www.learnrxjs.io/operators/transformation/mergemap.html

**Comment by cquillen2003** [comment]
Okay, I'll take a look.  Thanks!
